### ISSUE TITLE
为啥一直报超时？

### ISSUE THREAD

**Issue by johntaiii** [bluedazzle/wechat_sender#7]
File "wx_sender.py", line 3, in <module>
    Sender().send("Hello From Wechat Sender")
  File "/Library/Python/2.7/site-packages/wechat_sender/sender.py", line 60, in send
    res = requests.post(url, data=data, timeout=self.timeout)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 516, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=10245): Read timed out. (read timeout=5)

**Comment by bluedazzle** [comment]
方便提供下代码和系统环境嘛？

**Comment by bluedazzle** [comment]
@johntaiii

**Comment by johntaiii** [comment]
你好，就是示例代码

`#coding: utf-8` 
`from wechat_sender import Sender` 
`Sender().send("Hello From Wechat Sender")`

![image](https://user-images.githubusercontent.com/2558009/27000073-b2efaa82-4ddb-11e7-9145-ca96d2c6cc19.png)

运行环境是Python 2.7.10 macOS10.12.5

谢谢

**Comment by bluedazzle** [comment]
在另一个脚本运行 listen 启动 wechat_sender 服务了嘛？
```
from wxpy import *
from wechat_sender import *
bot = Bot()
listen(bot)
# 之后 wechat_sender 将持续运行等待接收外部消息
```
像这样 @johntaiii

**Comment by johntaiii** [comment]
我是直接在wxpy里listen的

![image](https://user-images.githubusercontent.com/2558009/27000232-883a6ff8-4ddf-11e7-941d-08848de97d8c.png)

**Comment by bluedazzle** [comment]
你这个 wxpy 的脚本也是跑在本机的嘛？如果不在同一台机器上需要给 Sender 指定 host @johntaiii

**Comment by johntaiii** [comment]
都是在本机上跑的..

**Comment by bluedazzle** [comment]
很奇怪，看起来像是 wechat_Sender 服务没有跑起来，你给 listen 所在的脚本加上
```
import logging
logging.basicConfig(level=logging.DEBUG)
```
然后再跑看看是不是报错了

**Comment by johntaiii** [comment]
![image](https://user-images.githubusercontent.com/2558009/27001428-4bf34bf6-4dfc-11e7-9742-3ada1cb849f8.png)
wxpy跑起来后又挂了....

**Comment by bluedazzle** [comment]
你 listen 的端口被占用了，换一个 listen(port=xxxx) 在 listen 里加这个参数端口号找个空闲的
