### ISSUE TITLE
手机客户端推出，服务也退出

### ISSUE THREAD

**Issue by AsherYang** [bluedazzle/wechat_sender#9]
你好，请教两个问题：
1. 当手机扫码登陆成功后，退出登录，listen服务也退出。这就要求有一台手机必须一直挂着这个微信号。请问有没有什么办法退出登录，服务不退出的方式
2. 设置listen receivers 为list 时，文档描述会发给默认第一个人，经试用测试只发给第一个人， 那有没有什么方法发给list中全部的人。 如果只能发给一个人，那这个list的作用就没有了。

**Comment by bluedazzle** [comment]
你好，
1、目前没有办法，因为微信本身有限制，即使你用 pc 登录，当你手机退出时 pc 也会退出的。
2、下个版本会更新 sender 多 receiver 功能。

**Comment by bluedazzle** [comment]
@AsherYang

**Comment by AsherYang** [comment]
好的，多谢
